;; This code was automatically generated by the 'metav' library.
(ns talltale.meta)

(def module-name "talltale")
(def path ".")
(def version "0.4.2")
(def tag "v0.4.2")
(def generated-at "2019-07-10T19:35:47Z")
