;; This code was automatically generated by the 'metav' library.
(ns talltale.meta)

(def module-name "talltale")
(def path ".")
(def version "0.5.8")
(def tag "v0.5.8")
(def generated-at "2021-12-16T21:23:57Z")
