;; This code was automatically generated by the 'metav' library.
(ns talltale.meta)

(def module-name "talltale")
(def path ".")
(def version "0.5.14")
(def tag "v0.5.14")
(def generated-at "2023-12-18T12:06:51Z")
