;; This code was automatically generated by the 'metav' library.
(ns talltale.meta)

(def module-name "talltale")
(def path ".")
(def version "0.5.0")
(def tag "v0.5.0")
(def generated-at "2020-10-01T13:04:53Z")
