;; This code was automatically generated by the 'metav' library.
(ns talltale.meta)

(def module-name "talltale")
(def path ".")
(def version "0.5.6")
(def tag "v0.5.6")
(def generated-at "2021-12-16T21:07:15Z")
