;; This code was automatically generated by the 'metav' library.
(ns talltale.meta)

(def module-name "talltale")
(def path ".")
(def version "0.5.4")
(def tag "v0.5.4")
(def generated-at "2021-03-12T09:33:00Z")
